name: MystiCraft
version: @version@
description: MystiCraft is an all-in-one magic plugin providing magic spells and items that users can use on RPG and survival servers alike

author: minnymin3

main: com.mcardy.mystic.MystiCraft
load: STARTUP